# Generated by Django 3.0.7 on 2020-06-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sms', '0002_consent_locator'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoing',
            name='schedule_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Schedule datetime'),
        ),
    ]
