# Generated by Django 3.0.7 on 2020-06-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_sms', '0003_outgoing_schedule_datetime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consent',
        ),
        migrations.DeleteModel(
            name='Locator',
        ),
    ]
